#!/bin/bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
if [[ $USER != root ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
dd if=/dev/urandom of=$(pwd)/test.bin count=250000
mkdir $(pwd)/audit
mkdir $(pwd)/temp
mkdir $(pwd)/.ssh
mkdir /root/.ssh
chmod 666 $(pwd)/audit
chmod 666 $(pwd)/temp
sed -i 's_Port 2222_Port 22_g' /etc/ssh/sshd_config
sed -i 's\#AuthorizedKeysFile	%h/.ssh/authorized_keys\AuthorizedKeysFile	%h/.ssh/authorized_keys\g' /etc/ssh/sshd_config
sed -i 's\MaxStartups 10:30:60\MaxStartups 30:30:60\g' /etc/ssh/sshd_config
systemctl enable ssh
systemctl start ssh
exit 0
